[package]
name = "cosworth_example"
version = "0.1.1"
authors = ["Gus Cost <guscost@gmail.com>"]

[dependencies]
cosworth = "0.1.1"
actix-web = { version = "0.7.4", features = ["alpn"] }
diesel = { version = "1.3.2", features = ["postgres", "r2d2", "uuid"] }
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.26"
