[package]
name = "cosworth"
version = "0.1.0"
authors = ["Gus Cost <guscost@gmail.com>"]
description = "A tool for making web services"
repository = "https://github.com/guscost/cosworth"
license-file = "./LICENSE"

[dependencies]
diesel = "1.3.2"
hyper = "0.12.7"
serde = "1.0.70"
