[package]
name = "cosworth"
version = "0.1.0"
authors = ["Gus Cost <guscost@gmail.com>"]
description = "A tool for making web services"
repository = "https://github.com/guscost/cosworth"
license = "MIT"

[dependencies]
actix-web = "0.7.3"
diesel = "1.3.2"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
